clear; clc; close all;

data = readtable('scenario_paths.csv', 'TextType', 'string');
data.date = datetime(data.date, 'InputFormat', 'yyyy-MM-dd');

baseline = data(data.scenario == "baseline", :);
g = baseline.g_t;

fig = figure;
hold on;

area(baseline.date, g, ...
    'FaceColor', [0.82, 0.90, 1.00], ...
    'EdgeColor', [0.20, 0.45, 0.80], ...
    'LineWidth', 1.5, ...
    'DisplayName', 'Normalized Supply-Demand Gap');

yline(0, '--', ...
    'Color', [0.35, 0.35, 0.35], ...
    'LineWidth', 1.2, ...
    'DisplayName', 'Equilibrium Line');

xline(datetime(2026, 2, 28), '--k', 'Conflict Start', ...
    'LineWidth', 1.2, ...
    'LabelVerticalAlignment', 'bottom', ...
    'LabelHorizontalAlignment', 'left');

legend('Location', 'northeast');
ax = gca;
apply_plot_style(fig, ax, 'Dynamic Evolution of Supply-Demand Gap', 'Normalized Gap g_t');

saveas(fig, 'plot_07_supply_demand_gap.png');
