clear; clc; close all;

data = readtable('final_fine_best_simulation.csv', 'TextType', 'string');
data.date = datetime(data.date, 'InputFormat', 'yyyy-MM-dd');

simPrice = data.sim_price;
actualPrice = data.actual_close;

validActual = ~ismissing(actualPrice);

fig = figure;
hold on;

plot(data.date, simPrice, ...
    'LineWidth', 2.2, ...
    'Color', [0.10, 0.35, 0.80], ...
    'DisplayName', 'Model Price');

plot(data.date(validActual), actualPrice(validActual), ...
    'o-', ...
    'LineWidth', 1.8, ...
    'MarkerSize', 5.5, ...
    'Color', [0.85, 0.25, 0.10], ...
    'MarkerFaceColor', [0.85, 0.25, 0.10], ...
    'DisplayName', 'Actual Price');

xline(datetime(2026, 2, 28), '--k', 'Conflict Start', ...
    'LineWidth', 1.2, ...
    'LabelVerticalAlignment', 'bottom', ...
    'LabelHorizontalAlignment', 'left');

legend('Location', 'northwest');

ax = gca;
apply_plot_style(fig, ax, 'Brent Crude Oil: Actual vs Model Price', 'Price (USD/barrel)');

saveas(fig, 'plot_01_actual_vs_model.png');
