clear; clc; close all;

data = readtable('scenario_paths.csv', 'TextType', 'string');
data.date = datetime(data.date, 'InputFormat', 'yyyy-MM-dd');

baseline = data(data.scenario == "baseline", :);

fig = figure;
hold on;

plot(baseline.date, baseline.L_t, ...
    'LineWidth', 2.2, ...
    'Color', [0.80, 0.20, 0.20], ...
    'DisplayName', 'Supply Disruption L_t');

plot(baseline.date, baseline.R_t, ...
    'LineWidth', 2.0, ...
    'Color', [0.15, 0.45, 0.85], ...
    'DisplayName', 'Reserve Release R_t');

plot(baseline.date, baseline.C_t, ...
    'LineWidth', 2.0, ...
    'Color', [0.10, 0.60, 0.30], ...
    'DisplayName', 'Inventory Release C_t');

plot(baseline.date, baseline.B_t, ...
    'LineWidth', 2.0, ...
    'Color', [0.90, 0.55, 0.10], ...
    'DisplayName', 'Bypass Recovery B_t');

plot(baseline.date, baseline.Q_t * 1000, ...
    '--', ...
    'LineWidth', 2.0, ...
    'Color', [0.55, 0.20, 0.75], ...
    'DisplayName', 'Demand Cut Q_t (\times1000)');

xline(datetime(2026, 2, 28), '--k', 'Conflict Start', ...
    'LineWidth', 1.2, ...
    'LabelVerticalAlignment', 'bottom', ...
    'LabelHorizontalAlignment', 'left');

legend('Location', 'eastoutside');
ax = gca;
apply_plot_style(fig, ax, 'Mechanism Decomposition over Time', 'Magnitude');

saveas(fig, 'plot_09_mechanism_decomposition.png');
