clear; clc; close all;

data = readtable('scenario_summary.csv', 'TextType', 'string');

displayNames = strings(height(data), 1);
displayNames(data.scenario == "baseline") = "Baseline";
displayNames(data.scenario == "no_buffer") = "No Buffer";
displayNames(data.scenario == "supply_buffer_only") = "Supply Buffer Only";
displayNames(data.scenario == "no_inventory_buffer") = "No Inventory Buffer";
displayNames(data.scenario == "no_late_demand_cut") = "No Late Demand Cut";

tableData = table( ...
    displayNames, ...
    round(data.peak_price, 2), ...
    data.peak_date, ...
    round(data.mid_mean, 2), ...
    round(data.late_mean, 2), ...
    round(data.end_price, 2), ...
    'VariableNames', {'Scenario', 'PeakPrice', 'PeakDate', 'MidMean', 'LateMean', 'EndPrice'});

fig = figure('Color', 'w', 'Position', [120, 120, 980, 260]);
uitable('Data', table2cell(tableData), ...
    'ColumnName', tableData.Properties.VariableNames, ...
    'Units', 'normalized', ...
    'Position', [0.02, 0.02, 0.96, 0.90], ...
    'FontSize', 11, ...
    'RowName', []);

annotation('textbox', [0.02, 0.92, 0.96, 0.06], ...
    'String', 'Scenario Comparison Summary', ...
    'LineStyle', 'none', ...
    'FontSize', 15, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center');

saveas(fig, 'plot_05_scenario_summary_table.png');
